# Plan-only tests for the platform layer. Nothing is created and no deployment has to exist.
#
# Unlike the spoke suite, this one mocks azuread as well, so it does NOT require `az login` or directory read access. The
# module takes databricks_service_principal_object_id for exactly that reason: mocking
# data.azuread_application_published_app_ids.well_known is awkward because its `result` is a map indexed by
# ["AzureDataBricks"], and an empty mock map makes that index fail at plan time. Supplying the object ID skips both data
# sources via their count.

mock_provider "azurerm" {
  mock_data "azurerm_client_config" {
    defaults = {
      tenant_id = "00000000-0000-0000-0000-000000000000"
      object_id = "00000000-0000-0000-0000-000000000000"
    }
  }

  # azurerm_role_assignment parses `scope` as an ARM resource ID, so the mocked vault needs a well-formed one rather than
  # the random string the mock would otherwise generate.
  mock_resource "azurerm_key_vault" {
    defaults = {
      id        = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-dbxtest-security/providers/Microsoft.KeyVault/vaults/kv-mock"
      vault_uri = "https://kv-mock.vault.azure.net/"
    }
  }

  # Same reason: the private endpoint's private_dns_zone_group parses each zone ID as an ARM resource ID.
  mock_resource "azurerm_private_dns_zone" {
    defaults = {
      id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-dbxtest-security/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"
    }
  }
}

mock_provider "azuread" {}

# The key resources read their versioned URI out of the ARM response, so the mock has to supply an `output` shaped like
# that response. Without it the versioned-key-ID outputs fail on a null value.
mock_provider "azapi" {
  mock_resource "azapi_resource" {
    defaults = {
      output = {
        properties = {
          keyUriWithVersion = "https://kv-mock.vault.azure.net/keys/mock-key/00000000000000000000000000000000"
        }
      }
    }
  }
}

variables {
  subscription_id = "00000000-0000-0000-0000-000000000000"
  location        = "eastus2"
  resource_suffix = "dbxtest"

  # Skips the live Microsoft Graph lookup - see the comment above
  databricks_service_principal_object_id = "11111111-1111-1111-1111-111111111111"

  # Pre-existing spoke networking. This layer does not create it: the network team builds the spoke VNets first, because
  # peering them to the hub needs permissions on the hub network that the Databricks provisioner does not hold.
  #
  # Set explicitly here, including create_key_vault_private_endpoint, because terraform test auto-loads terraform.tfvars
  # from this directory - so a deployment that has the endpoint switched off must not silently disable it for the tests.
  create_key_vault_private_endpoint    = true
  key_vault_private_endpoint_subnet_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-spoke/providers/Microsoft.Network/virtualNetworks/vnet-spoke/subnets/privatelink"
  spoke_virtual_network_ids = {
    spoke1 = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-spoke/providers/Microsoft.Network/virtualNetworks/vnet-spoke"
  }
}

# Uses `command = apply` rather than `plan` because the role-assignment scope assert below compares two resource IDs,
# which are not known until after apply. Every provider in this suite is mocked, so this creates nothing - the IDs are
# generated by the mocks.
run "plan_platform_defaults" {
  command = apply

  # ---- Vault posture. Migrated from the spoke suite's plan_test_cmk_create_in_spoke, which this replaces. ----

  # Purge protection cannot be disabled once set, and a purged key would permanently break the compute of every
  # workspace using this shared vault
  assert {
    condition     = module.vault.purge_protection_enabled
    error_message = "Purge protection must be enabled on the shared Key Vault"
  }

  # The vault is closed to the public internet, with no IP exceptions. Key creation still works because it goes through
  # ARM, which the vault firewall does not govern.
  assert {
    condition     = module.vault.public_network_access_enabled == false
    error_message = "The shared Key Vault must not allow public network access"
  }

  assert {
    condition     = module.vault.network_acls_default_action == "Deny"
    error_message = "The shared Key Vault firewall must deny by default"
  }

  # Both CMK consumers - the Databricks control plane and the Disk Encryption Set - sit outside every spoke VNet and
  # reach the vault via the trusted-services bypass, not a private endpoint. Losing this breaks cluster startup.
  assert {
    condition     = module.vault.network_acls_bypass == "AzureServices"
    error_message = "The shared Key Vault must allow the AzureServices bypass, which is what permits CMK access"
  }

  # One key per CMK scope - managed services, DBFS root, managed disk - so each can be rotated or revoked independently
  assert {
    condition     = length(distinct(module.vault.key_names)) == 3
    error_message = "Managed services, DBFS root, and managed disk must each use a distinct key"
  }

  # ---- RBAC. New with the shared-vault design. ----

  assert {
    condition     = module.vault.rbac_authorization_enabled
    error_message = "The shared Key Vault must use Azure RBAC, not access policies: it is shared across workspaces and Terraform states"
  }

  # The important one. Vault-scoped, NOT key-scoped. Per the Key Vault RBAC guide, assigning roles on individual keys is
  # not recommended, and its FAQ says object-scope assignments do not isolate application teams - with one shared key set
  # they would isolate nothing while breaking vault-level administration. This assert is the only automated defence
  # against someone "tightening" the design into key-scoped assignments.
  assert {
    condition     = module.vault.cmk_role_assignment_scope == module.vault.key_vault_id
    error_message = "The CMK role assignment must be scoped to the vault, not to an individual key"
  }

  assert {
    condition     = module.vault.cmk_role_definition_name == "Key Vault Crypto Service Encryption User"
    error_message = "CMK wrap/unwrap requires the Key Vault Crypto Service Encryption User role"
  }

  # ---- Private access to the vault. Owned here rather than per spoke. ----

  # One endpoint and one zone for the shared vault. Per-spoke endpoints would each register an A-record named after the
  # same target vault, so a shared zone would resolve one spoke's lookups to another spoke's unreachable NIC.
  assert {
    condition     = output.key_vault_private_endpoint.dns_zone_name == "privatelink.vaultcore.azure.net"
    error_message = "The platform layer should own the privatelink.vaultcore.azure.net zone for the shared vault"
  }

  # The zone lives with the vault, not in a spoke resource group
  assert {
    condition     = output.key_vault_private_endpoint.resource_group_name == output.security_resource_group_name
    error_message = "The vaultcore zone should be created in the security resource group alongside the vault"
  }

  # Adding a spoke is a VNet link, not a second zone
  assert {
    condition     = keys(output.key_vault_private_endpoint.linked_vnet_ids) == ["spoke1"]
    error_message = "Each spoke that resolves the vault privately should appear as a VNet link on the shared zone"
  }
}

# The endpoint is optional: CMK works without it, since neither unwrap call traverses a private endpoint and keys are
# created through ARM's control plane. Turning it off should also drop the subnet requirement.
run "plan_platform_no_private_endpoint" {
  command = plan

  variables {
    create_key_vault_private_endpoint    = false
    key_vault_private_endpoint_subnet_id = null
    spoke_virtual_network_ids            = {}
  }

  assert {
    condition     = length(module.vault_private_access) == 0
    error_message = "No private endpoint, zone, or VNet link should be created when create_key_vault_private_endpoint is false"
  }

  assert {
    condition     = output.key_vault_private_endpoint == null
    error_message = "The private endpoint output should be null when the endpoint is not created"
  }
}

# An explicit vault name is strongly preferred for a shared singleton, so confirm the override is wired through rather
# than being silently ignored in favour of the generated random-suffixed name.
run "plan_platform_explicit_names" {
  command = plan

  variables {
    key_vault_name  = "kv-dbx-test-eastus2"
    key_name_prefix = "kvk-dbx-test"
  }

  assert {
    condition     = module.vault.key_vault_name == "kv-dbx-test-eastus2"
    error_message = "key_vault_name must override the generated vault name"
  }

  assert {
    condition     = alltrue([for n in module.vault.key_names : startswith(n, "kvk-dbx-test-adb-")])
    error_message = "key_name_prefix must override the generated key name prefix"
  }
}

# Deploying into a centrally-governed resource group, rather than creating one
run "plan_platform_existing_resource_group" {
  command = plan

  variables {
    create_security_resource_group        = false
    existing_security_resource_group_name = "rg-prod-security"
  }

  assert {
    condition     = length(azurerm_resource_group.security) == 0
    error_message = "No resource group should be created when create_security_resource_group is false"
  }

  assert {
    condition     = output.security_resource_group_name == "rg-prod-security"
    error_message = "The existing resource group name should be used and surfaced as an output"
  }
}
