output "security_resource_group_name" {
  description = "Resource group holding the shared vault. Spokes pass this as security_resource_group_name when placing their access connectors here."
  value       = local.resource_group_name
}

output "location" {
  description = "Region of the shared vault. Every spoke consuming this layer must deploy into the same region."
  value       = var.location
}

output "key_vault_id" {
  description = "ARM resource ID of the shared Key Vault"
  value       = module.vault.key_vault_id
}

output "key_vault_name" {
  description = "Name of the shared Key Vault"
  value       = module.vault.key_vault_name
}

output "key_vault_uri" {
  description = "URI of the shared Key Vault"
  value       = module.vault.key_vault_uri
}

output "cmk_key_ids" {
  description = "Versioned IDs of the three shared CMKs. Versioned because Databricks requires a specific key version, never \"latest\" - so a rotation changes these and the consuming spokes must be updated."
  value = {
    managed_services_key_id = module.vault.managed_services_key_id
    dbfs_root_key_id        = module.vault.dbfs_root_key_id
    managed_disk_key_id     = module.vault.managed_disk_key_id
  }
}

# ------------------------------------------------------------------
# Handoff to the spoke configurations
#
# Modelled on the hub_peering_command output in tf/outputs.tf: where this repository crosses an ownership boundary, it
# emits a copy-pasteable artefact for the next actor rather than assuming they will assemble it correctly by hand.
#
# Plain variables are used rather than terraform_remote_state deliberately. Remote state would give every spoke principal
# read access to this entire state file, not just these values, which inverts the least-privilege model that motivates
# splitting the states in the first place. It would also couple a spoke `plan` to this backend's availability and
# credentials, breaking the spoke's mock tests, which are designed to run with no deployed infrastructure.
output "spoke_tfvars_snippet" {
  description = "Copy-paste into each spoke's var file. Regenerate and re-apply the spokes after any key rotation."

  value = <<-EOT
    # Shared platform Key Vault. Generated by `terraform output -raw spoke_tfvars_snippet` in tf/platform.
    # The spoke's `location` must equal "${var.location}".
    security_resource_group_name = "${local.resource_group_name}"

    platform_cmk = {
      key_vault_id            = "${module.vault.key_vault_id}"
      key_vault_uri           = "${module.vault.key_vault_uri}"
      managed_services_key_id = "${module.vault.managed_services_key_id}"
      managed_disk_key_id     = "${module.vault.managed_disk_key_id}"
      dbfs_root_key_name      = "${module.vault.dbfs_root_key_name}"
      dbfs_root_key_version   = "${module.vault.dbfs_root_key_version}"
    }
  EOT
}
